package com.poligon.local;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.view.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends Activity {
 private WebView web;private final ExecutorService pool=Executors.newFixedThreadPool(4);private boolean loaded=false;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff111318);getWindow().setNavigationBarColor(0xff171a1f);web=new WebView(this);web.setBackgroundColor(0xff111318);setContentView(web);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);WebView.setWebContentsDebuggingEnabled(BuildConfig.DEBUG);web.addJavascriptInterface(new Bridge(),"Android");
 web.setWebViewClient(new WebViewClient(){
 public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !r.getUrl().toString().startsWith("https://app.poligon.local/");}
 public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{Uri u=r.getUrl();if(!"app.poligon.local".equals(u.getHost()))return blocked();String path=u.getPath();String name=path.equals("/")?"index.html":path.startsWith("/assets/")?path.substring(8):"";if(!name.matches("[a-zA-Z0-9_.-]+"))return blocked();String mime=name.endsWith(".js")?"application/javascript":name.endsWith(".css")?"text/css":name.endsWith(".svg")?"image/svg+xml":"text/html";Map<String,String> h=new HashMap<>();h.put("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'");return new WebResourceResponse(mime,"UTF-8",200,"OK",h,getAssets().open("web/"+name));}catch(Exception e){return blocked();}}
 public void onPageFinished(WebView v,String url){loaded=true;deliverIntent(getIntent());}
 });web.loadUrl("https://app.poligon.local/");if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=0)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},7);
 }
 private WebResourceResponse blocked(){return new WebResourceResponse("text/plain","UTF-8",403,"Forbidden",new HashMap<>(),new ByteArrayInputStream(new byte[0]));}
 protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(loaded)deliverIntent(i);}
 private void deliverIntent(Intent i){Uri u=i.getData();if(u!=null&&"poligon".equals(u.getScheme())&&"pair".equals(u.getHost()))web.evaluateJavascript("window.receivePair("+JSONObject.quote(u.getQueryParameter("url"))+","+JSONObject.quote(u.getQueryParameter("code"))+")",null);else if(Intent.ACTION_SEND.equals(i.getAction()))web.evaluateJavascript("window.receiveShared("+JSONObject.quote(i.getStringExtra(Intent.EXTRA_TEXT))+ ")",null);}
 class Bridge { @JavascriptInterface public void request(String id,String raw){pool.execute(()->{JSONObject out=new JSONObject();try{JSONObject r=new JSONObject(raw);Object data=LocalAgent.get(MainActivity.this).request(r);out.put("data",data);}catch(Exception e){try{out.put("error",e.getMessage()==null?e.toString():e.getMessage());}catch(Exception ignored){}}final String script="window.nativeResult("+JSONObject.quote(id)+","+out+")";runOnUiThread(()->web.evaluateJavascript(script,null));});} }
 @Override public void onBackPressed(){web.evaluateJavascript("document.querySelector('[data-page=assistant]').click()",null);}
 protected void onDestroy(){web.removeJavascriptInterface("Android");web.destroy();pool.shutdown();super.onDestroy();}
}
